# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(306, 74)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.ext_lbl = QtWidgets.QLabel(Dialog)
        self.ext_lbl.setObjectName("ext_lbl")
        self.gridLayout.addWidget(self.ext_lbl, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 1, 1, 1)
        self.dwpath_led = QtWidgets.QLineEdit(Dialog)
        self.dwpath_led.setObjectName("dwpath_led")
        self.gridLayout.addWidget(self.dwpath_led, 0, 1, 1, 1)
        self.dpath_lbl = QtWidgets.QLabel(Dialog)
        self.dpath_lbl.setObjectName("dpath_lbl")
        self.gridLayout.addWidget(self.dpath_lbl, 0, 0, 1, 1)
        self.ext_cb = QtWidgets.QComboBox(Dialog)
        self.ext_cb.setObjectName("ext_cb")
        self.ext_cb.addItem("")
        self.ext_cb.addItem("")
        self.ext_cb.addItem("")
        self.gridLayout.addWidget(self.ext_cb, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.ext_cb.setCurrentIndex(1)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.ext_lbl.setText(_translate("Dialog", "Extension"))
        self.dpath_lbl.setText(_translate("Dialog", "Download Path"))
        self.ext_cb.setItemText(0, _translate("Dialog", "Auto Check"))
        self.ext_cb.setItemText(1, _translate("Dialog", "mp4"))
        self.ext_cb.setItemText(2, _translate("Dialog", "webm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
